import './globals.css'

import { Geist, Geist_Mono } from 'next/font/google'

import { Aside } from '@/app/dashboard/components/Aside'
import type { Metadata } from 'next'
import { TasksProvider } from '@/shared/hooks/useTasksContext'
import { ReactNode } from 'react'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} flex flex-col antialiased`}
      >
        <div className="flex h-screen w-full flex-row">
          <TasksProvider>
            <Aside />
            {children}
          </TasksProvider>
        </div>
      </body>
    </html>
  )
}
